import Head from "next/head";
import FeaturesSection from '../components/layout/FeaturesSection';
import VoicesSection from '../components/layout/VoicesSection';
import CampusLifeSection from '../components/layout/CampusLifeSection';
import NavBar from '../components/layout/NavBar';
import Footer from '../components/layout/Footer';
import HeroSection from "@/components/layout/HeroSection";
import StepsSection from "@/components/layout/StepsSection";
import AccessSection from "@/components/layout/AccessSection";
import ScheduleSection from "@/components/layout/ScheduleSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>JFUTオープンキャンパス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div style={{
        paddingTop: 56,
        overscrollBehavior: 'none',
        WebkitOverflowScrolling: 'touch'
      }}>
        <section id="hero"><HeroSection /></section>
        <section id="features"><FeaturesSection /></section>
        <section id="steps"><StepsSection /></section>
        <section id="schedule"><ScheduleSection /></section>
        <section id="voices"><VoicesSection /></section>
        <section id="campus-life"><CampusLifeSection /></section>
        <section id="access"><AccessSection /></section>
      </div>
      <Footer />
    </>
  );
}
